site_name: NeuralForge Documentation
site_description: Professional AI & Automation Toolkit for Apple Silicon
site_url: https://autogio.github.io/neuralforge
repo_url: https://github.com/AUTOGIO/neuralforge
repo_name: AUTOGIO/neuralforge

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Features:
    - Neural Engine Monitor: features/neural-engine-monitor.md
    - AI Memory System: features/ai-memory-system.md
    - Core ML Integration: features/core-ml-integration.md
  - API Reference: api/
  - Examples: examples/
  - Contributing: ../CONTRIBUTING.md
  - Security: ../SECURITY.md
  - Changelog: ../CHANGELOG.md

plugins:
  - search
  - mkdocstrings
